### ISSUE TITLE
2.10.65 causing TypeError in integer2bits due to changes in core.py

### ISSUE THREAD

**Issue by midimopo** [construct/construct#923]
Hi,

We utilize construct as a dependency in one of our tools and since the changes applied in commit f90db55c19e4e59c0631d7364638a579e3501297 we started getting an error. Below i am pasting part of the log beginning at the point where we enter construct. Due to copyrights i am not sure if i can share the full log.
I can assure you though that nothing has changed in our package since almost a year.

As i see it changing _return self.defersubcon._build(obj, stream, context, path)_ to _return self.buildfunc(obj, stream, context)_ in core.py line 790 broke something and some variables are used uninitialised

element_container below is of type construct.Container
...
```
    object_def_payload_bytes = object_def_struct.build(element_container)
.tox/py36-dev/lib/python3.6/site-packages/construct/core.py:336: in build
    self.build_stream(obj, stream, **contextkw)
.tox/py36-dev/lib/python3.6/site-packages/construct/core.py:348: in build_stream
    self._build(obj, stream, context, "(building)")
.tox/py36-dev/lib/python3.6/site-packages/construct/core.py:790: in _build
    return self.buildfunc(obj, stream, context)
:24: in buildall
    ???
.tox/py36-dev/lib/python3.6/site-packages/construct/core.py:5170: in _build
    buildret = self.subcon._build(obj, stream2, context, path)
.tox/py36-dev/lib/python3.6/site-packages/construct/core.py:2144: in _build
    buildret = sc._build(subobj, stream, context, path)
.tox/py36-dev/lib/python3.6/site-packages/construct/core.py:2657: in _build
    return self.subcon._build(obj, stream, context, path)
.tox/py36-dev/lib/python3.6/site-packages/construct/core.py:2428: in _build
    buildret = self.subcon._build(e, stream, context, path)
.tox/py36-dev/lib/python3.6/site-packages/construct/core.py:2144: in _build
    buildret = sc._build(subobj, stream, context, path)
.tox/py36-dev/lib/python3.6/site-packages/construct/core.py:2657: in _build
    return self.subcon._build(obj, stream, context, path)
.tox/py36-dev/lib/python3.6/site-packages/construct/core.py:3857: in _build
    return sc._build(obj, stream, context, path)
.tox/py36-dev/lib/python3.6/site-packages/construct/core.py:790: in _build
    return self.buildfunc(obj, stream, context)
:131: in buildall
    ???
:72: in build_struct_2
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

number = None, width = 10, signed = False

    def integer2bits(number, width, signed=False):
        r"""
        Converts an integer into its binary representation in a bit-string. Width is the amount of bits to generate. Each bit is represented as either \\x00 or \\x01. The most significant bit is first, big-endian. This is reverse to `bits2integer`.
    
        Examples:
    
            >>> integer2bits(19, 8)
            b'\x00\x00\x00\x01\x00\x00\x01\x01'
        """
        if width < 0:
            raise ValueError(f"width {width} must be non-negative")
        if width == 0:
            return b""
    
        if signed:
            min = -(2 ** width // 2)
            max = 2 ** width // 2 - 1
        else:
            min = 0
            max = 2 ** width - 1
>       if not min <= number <= max:
E       TypeError: '<=' not supported between instances of 'int' and 'NoneType'

.tox/py36-dev/lib/python3.6/site-packages/construct/lib/binary.py:26: TypeError
```

--------------------------------

Our workaround for now is to stick to v.2.10.64

Cheers,
Michalis

**Comment by arekbulski** [comment]
I suspect the error is on your side. The log shows you are passing None as a number to BitsInteger? Please elaborate if you are using BitsInteger, using swapped parameter, or using compilation. This will help.

**Comment by arekbulski** [comment]
Fixed, and some other classes too. Please recheck.

**Comment by midimopo** [comment]
Hi thanks for taking a look. I run the tests with the latest version i still get the same issue.
It might be that due to recent changes the way we create element_container is not valid anymore. I will take a look on my side.

**Comment by arekbulski** [comment]
You could share the code with me over private email if you like. I will keep it confidential.
